---
- block:
  - name: Get Zerotier NodeID
    shell: zerotier-cli info | awk '{print $3}'
    register: nodeid
    changed_when: false

  - name: Set NodeID as fact
    set_fact:
      zerotier_node_id: "{{ nodeid.stdout }}"

  - name: Authorize members to network
    uri:
      url: "{{ zerotier_controller_url }}/network/{{ zerotier_network_id }}/member/{{ zerotier_node_id }}"
      method: POST
      headers:
        X-ZT1-Auth: "{{ zerotier_accesstoken }}"
      body:
          authorized: "{{ zerotier_authorize_member }}"
      body_format: json
      register: auth_apiresult
      become: false
    delegate_to: "{{ zerotier_api_delegate }}"

  - name: Configure members in network
    uri:
      url: "{{ zerotier_controller_url }}/network/{{ zerotier_network_id }}/member/{{ zerotier_node_id }}"
      method: POST
      headers:
        X-ZT1-Auth: "{{ zerotier_accesstoken }}"
      body:
        activeBridge: "{{ zerotier_active_bridge }}"
        ipAssignments: "{{ zerotier_member_ip_assignments | default([]) | list }}"
      body_format: json
      register: conf_apiresult
      become: false
    delegate_to: "{{ zerotier_api_delegate }}"

  when:
  - zerotier_accesstoken is defined
  - not ansible_check_mode
  tags:
  - configuration
